apiVersion: v1
kind: Namespace
metadata:
  name: tilloo-services
  labels:
    name: tilloo-services
---
apiVersion: v1
kind: Namespace
metadata:
  name: tilloo-jobs
  labels:
    name: tilloo-jobs
---
