name: tilloo
on:
  push:
  pull_request:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Docker login
        run: docker login ghcr.io --username ${{ secrets.GH_CR_USERNAME }} --password ${{ secrets.GH_CR_PAT }}
      - name: Run Buildx
        run: |
          docker buildx build --platform linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64 --file Dockerfile --tag ghcr.io/chriskinsman/tilloo:${GITHUB_REF##*/}-3.1.$GITHUB_RUN_NUMBER --output "type=image,push=true" .
          docker pull ghcr.io/chriskinsman/tilloo:${GITHUB_REF##*/}-3.1.$GITHUB_RUN_NUMBER
          docker tag ghcr.io/chriskinsman/tilloo:${GITHUB_REF##*/}-3.1.$GITHUB_RUN_NUMBER ghcr.io/chriskinsman/tilloo:${GITHUB_REF##*/}-latest
          docker push ghcr.io/chriskinsman/tilloo:${GITHUB_REF##*/}-latest
      - name: Update latest tag
        if: startsWith(github.ref, 'refs/heads/master')
        run: |
          docker pull ghcr.io/chriskinsman/tilloo:${GITHUB_REF##*/}-3.1.$GITHUB_RUN_NUMBER
          docker tag ghcr.io/chriskinsman/tilloo:${GITHUB_REF##*/}-3.1.$GITHUB_RUN_NUMBER ghcr.io/chriskinsman/tilloo:latest
          docker push ghcr.io/chriskinsman/tilloo:latest